### ISSUE TITLE
After docker compose up, webui and lib failed to start.

### ISSUE THREAD

**Issue by 228983380** [signalorange/rocm-sd#1]
```bash
root@wkp-PC:~/rocm-sd# docker compose logs -t -f
automatic1111-1  | 2024-10-19T18:12:25.756219657Z Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
automatic1111-1  | 2024-10-19T18:12:25.756279001Z Version: v1.10.0
automatic1111-1  | 2024-10-19T18:12:25.756286762Z Commit hash: c19d04436496ab29ddca4758a792831ae41b31de
automatic1111-1  | 2024-10-19T18:12:25.812982359Z Launching Web UI with arguments: --data-dir /stable-diffusion-webui/data --listen --port 7860 --lowvram --enable-insecure-extension-access --api --skip-torch-cuda-test --upcast-sampling --opt-sub-quad-attention
automatic1111-1  | 2024-10-19T18:12:30.617381445Z /usr/local/lib/python3.10/dist-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
automatic1111-1  | 2024-10-19T18:12:30.617443364Z   warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
automatic1111-1  | 2024-10-19T18:12:30.791895042Z no module 'xformers'. Processing without...
automatic1111-1  | 2024-10-19T18:12:30.795285885Z no module 'xformers'. Processing without...
automatic1111-1  | 2024-10-19T18:12:30.826883609Z ***
automatic1111-1  | 2024-10-19T18:12:30.826908021Z *** Could not load settings
automatic1111-1  | 2024-10-19T18:12:30.826915977Z *** The config file "/stable-diffusion-webui/data/config.json" is likely corrupted
automatic1111-1  | 2024-10-19T18:12:30.826923521Z *** It has been moved to the "tmp/config.json"
automatic1111-1  | 2024-10-19T18:12:30.826930427Z *** Reverting config to default
automatic1111-1  | 2024-10-19T18:12:30.826937399Z ***
automatic1111-1  | 2024-10-19T18:12:30.827006937Z     Traceback (most recent call last):
automatic1111-1  | 2024-10-19T18:12:30.827022500Z       File "/stable-diffusion-webui/modules/launch_utils.py", line 248, in list_extensions
automatic1111-1  | 2024-10-19T18:12:30.827030508Z         with open(settings_file, "r", encoding="utf8") as file:
automatic1111-1  | 2024-10-19T18:12:30.827038042Z     IsADirectoryError: [Errno 21] Is a directory: '/stable-diffusion-webui/data/config.json'
automatic1111-1  | 2024-10-19T18:12:30.827045082Z
automatic1111-1  | 2024-10-19T18:12:30.827051339Z ---
automatic1111-1  | 2024-10-19T18:12:30.827057807Z Traceback (most recent call last):
automatic1111-1  | 2024-10-19T18:12:30.827064453Z   File "/stable-diffusion-webui/modules/launch_utils.py", line 248, in list_extensions
automatic1111-1  | 2024-10-19T18:12:30.827098709Z     with open(settings_file, "r", encoding="utf8") as file:
automatic1111-1  | 2024-10-19T18:12:30.827118357Z IsADirectoryError: [Errno 21] Is a directory: '/stable-diffusion-webui/data/config.json'
automatic1111-1  | 2024-10-19T18:12:30.827129774Z
automatic1111-1  | 2024-10-19T18:12:30.827139647Z During handling of the above exception, another exception occurred:
automatic1111-1  | 2024-10-19T18:12:30.827150576Z
automatic1111-1  | 2024-10-19T18:12:30.827160983Z Traceback (most recent call last):
automatic1111-1  | 2024-10-19T18:12:30.827168954Z   File "/stable-diffusion-webui/launch.py", line 48, in <module>
automatic1111-1  | 2024-10-19T18:12:30.827187752Z     main()
automatic1111-1  | 2024-10-19T18:12:30.827199181Z   File "/stable-diffusion-webui/launch.py", line 44, in main
automatic1111-1  | 2024-10-19T18:12:30.827209662Z     start()
automatic1111-1  | 2024-10-19T18:12:30.827216190Z   File "/stable-diffusion-webui/modules/launch_utils.py", line 465, in start
automatic1111-1  | 2024-10-19T18:12:30.827322349Z     import webui
automatic1111-1  | 2024-10-19T18:12:30.827331086Z   File "/stable-diffusion-webui/webui.py", line 13, in <module>
automatic1111-1  | 2024-10-19T18:12:30.827380804Z     initialize.imports()
automatic1111-1  | 2024-10-19T18:12:30.827391388Z   File "/stable-diffusion-webui/modules/initialize.py", line 35, in imports
automatic1111-1  | 2024-10-19T18:12:30.827433462Z     from modules import shared_init
automatic1111-1  | 2024-10-19T18:12:30.827440706Z   File "/stable-diffusion-webui/modules/shared_init.py", line 5, in <module>
automatic1111-1  | 2024-10-19T18:12:30.827479612Z     from modules import shared
automatic1111-1  | 2024-10-19T18:12:30.827486856Z   File "/stable-diffusion-webui/modules/shared.py", line 6, in <module>
automatic1111-1  | 2024-10-19T18:12:30.827534192Z     from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types
automatic1111-1  | 2024-10-19T18:12:30.827548595Z   File "/stable-diffusion-webui/modules/shared_cmd_options.py", line 9, in <module>
automatic1111-1  | 2024-10-19T18:12:30.827564623Z     script_loading.preload_extensions(extensions_dir, parser, extension_list=launch.list_extensions(launch.args.ui_settings_file))
automatic1111-1  | 2024-10-19T18:12:30.827571652Z   File "/stable-diffusion-webui/modules/launch_utils.py", line 254, in list_extensions
automatic1111-1  | 2024-10-19T18:12:30.827666097Z     os.replace(settings_file, os.path.join(script_path, "tmp", "config.json"))
automatic1111-1  | 2024-10-19T18:12:30.827676267Z FileNotFoundError: [Errno 2] No such file or directory: '/stable-diffusion-webui/data/config.json' -> '/stable-diffusion-webui/tmp/config.json'
comfyui-1        | 2024-10-19T18:12:27.305717791Z Total VRAM 8192 MB, total RAM 128790 MB
comfyui-1        | 2024-10-19T18:12:27.305812406Z pytorch version: 2.0.1
comfyui-1        | 2024-10-19T18:12:27.305906644Z Set vram state to: NORMAL_VRAM
comfyui-1        | 2024-10-19T18:12:27.306382330Z Device: cuda:0 Radeon RX 590 Series : native
comfyui-1        | 2024-10-19T18:12:27.559274852Z Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
comfyui-1        | 2024-10-19T18:12:28.472657563Z [Prompt Server] web root: /comfyui/web
comfyui-1        | 2024-10-19T18:12:28.968970246Z Starting server
comfyui-1        | 2024-10-19T18:12:28.969006089Z
comfyui-1        | 2024-10-19T18:12:28.969177962Z To see the GUI go to: http://0.0.0.0:7861
comfyui-1        | 2024-10-19T18:12:28.969378152Z To see the GUI go to: http://[::]:7861
iib-1            | 2024-10-19T18:12:25.690443060Z variables set as follows:
iib-1            | 2024-10-19T18:12:25.690501768Z PORT = 8080
iib-1            | 2024-10-19T18:12:25.690509740Z EXTRA_PATHS = /comfyui
iib-1            | 2024-10-19T18:12:25.690514286Z EXTRA_OPTIONS =
iib-1            | 2024-10-19T18:12:25.690518434Z
iib-1            | 2024-10-19T18:12:25.690522564Z checking default_host line in app.py:
iib-1            | 2024-10-19T18:12:25.691678897Z default_host = "0.0.0.0"
iib-1            | 2024-10-19T18:12:25.691791116Z
iib-1            | 2024-10-19T18:12:25.691890463Z checking .env file:
iib-1            | 2024-10-19T18:12:25.693290221Z IIB_ACCESS_CONTROL=enable
iib-1            | 2024-10-19T18:12:25.693444380Z
iib-1            | 2024-10-19T18:12:25.693453737Z checking python version
iib-1            | 2024-10-19T18:12:25.695973695Z Python 3.10.15
iib-1            | 2024-10-19T18:12:25.696225490Z
iib-1            | 2024-10-19T18:12:25.696232962Z launching app.py
iib-1            | 2024-10-19T18:12:26.442937120Z Traceback (most recent call last):
iib-1            | 2024-10-19T18:12:26.443024702Z   File "/root/git/sd-webui-infinite-image-browsing/app.py", line 299, in <module>
iib-1            | 2024-10-19T18:12:26.443031790Z     launch_app(**vars(args))
iib-1            | 2024-10-19T18:12:26.443035220Z   File "/root/git/sd-webui-infinite-image-browsing/app.py", line 257, in launch_app
iib-1            | 2024-10-19T18:12:26.443039342Z     app = app_utils.get_root_browser_app()
iib-1            | 2024-10-19T18:12:26.443043071Z   File "/root/git/sd-webui-infinite-image-browsing/app.py", line 168, in get_root_browser_app
iib-1            | 2024-10-19T18:12:26.443046951Z     self.wrap_app(app)
iib-1            | 2024-10-19T18:12:26.443050234Z   File "/root/git/sd-webui-infinite-image-browsing/app.py", line 134, in wrap_app
iib-1            | 2024-10-19T18:12:26.443053585Z     sd_webui_paths_check(sd_webui_config, self.sd_webui_path_relative_to_config)
iib-1            | 2024-10-19T18:12:26.443056858Z   File "/root/git/sd-webui-infinite-image-browsing/app.py", line 38, in sd_webui_paths_check
iib-1            | 2024-10-19T18:12:26.443060437Z     with codecs.open(sd_webui_config, "r", "utf-8") as f:
iib-1            | 2024-10-19T18:12:26.443063825Z   File "/usr/local/lib/python3.10/codecs.py", line 906, in open
iib-1            | 2024-10-19T18:12:26.443067242Z     file = builtins.open(filename, mode, buffering)
iib-1            | 2024-10-19T18:12:26.443070430Z IsADirectoryError: [Errno 21] Is a directory: '/config.json'

```

**Comment by lejacobroy** [comment]
the error ` Is a directory: '/config.json'` indicates that the "file" config.json is actualy a directory. I suspect that your docker-compose volume mapping has a problem, could you post it here? Add also an `ls -l` output for the folders `/Automatic1111/data`
